package org.osada.ui

import org.w3c.xhr.XMLHttpRequest

/**
 * OG's **custom scenario music** — `.xscn` `@127`, a NUL-terminated track name gated on
 * `opt_custom_music` (`@1009` bit 6). **81 deployed scenarios author one**, 688 corpus-wide across
 * 62 distinct names (`winter.mp3`, `amb_field.mp3`, `japan1.MUS`, `PG1.mp3`); OG resolves each in
 * the naming scenario's OWN efile `SOUND` directory and in the install's root `SOUND`, and nowhere
 * else — which is why a name that exists only in some other efile means silence, not that file.
 *
 * ## Licensed subset and manifest gate
 *
 * `README/read_me_first.html` in the OG install forbids redistributing sounds without the owner's
 * written permission. That permission was confirmed by the repository owner on 2026-09-01. Three
 * referenced MP3s present in the installed distribution now ship with a manifest at [MANIFEST_URL]
 * and cover 47 scenarios — 45 of them from their own efile, plus the two `eqp-olgcw` scenarios that
 * name `AFRICA2.mp3`, which is a recorded substitution rather than their author's file (see
 * `sounds/music/NOTICE.md`). Five referenced names have no source file in that install; they remain
 * silent, and the manifest prevents any request or 404 for them.
 *
 * ## Two normalisations, and why they are here rather than in the importer
 *
 * * **Case.** OG runs on Windows, where `Winter.MP3` and `winter.mp3` are the same file; the
 *   deployed web server is case-sensitive. Names are matched lower-cased.
 * * **Format.** `.MUS` is a DOS-era tracker format no browser plays, and 62 distinct authored names
 *   include several. A track whose extension is not [PLAYABLE] is refused rather than requested.
 *
 * Both are runtime concerns rather than import ones: `add_custom_music.py` deploys the author's own
 * string so the XML stays a faithful record of what was written, and a future converted `.ogg`
 * changes only the manifest.
 *
 * An unsupported or absent track falls back to what OSADA already does between battles, which is
 * silence — never to a rejected autoplay promise, which is what a naive `Audio.play()` on a missing
 * file produces.
 */
object ScenarioMusic {
    const val MANIFEST_URL = "resources/sounds/music/manifest.json"

    private const val MUSIC_PATH = "resources/sounds/music/"

    /** Extensions a browser will actually decode. `.MUS` is deliberately not among them. */
    private val PLAYABLE = setOf("mp3", "ogg", "m4a", "wav")

    private var available: Set<String>? = null

    /**
     * The URL for [track], or null when it is absent, unplayable, or not listed by the manifest.
     *
     * Public so a caller can tell "there is a track" from "it is playing", which the settings screen
     * would need before it can offer to turn scenario music off.
     */
    fun urlFor(track: String?): String? {
        val name = track?.trim()?.lowercase()?.takeIf { it.isNotEmpty() } ?: return null
        return candidates(name).firstOrNull { it in manifest() }?.let { MUSIC_PATH + it }
    }

    /**
     * The file names that may answer for an authored track name, best first.
     *
     * A playable name answers for itself and nothing else. An UNPLAYABLE one -- `.MUS`, the
     * DOS-era tracker format no browser decodes -- may be answered by a converted file of the same
     * stem, because that is the only way the 31 scenarios naming `china1.MUS` and `Jungle_2.MUS`
     * can ever have their author's music: the name is in the scenario XML, which is a faithful
     * record of the source and is regenerated by the importers, so it cannot be edited to point at
     * the conversion.
     *
     * The manifest is still the only gate. A candidate that is not listed is never requested, so a
     * scenario with no conversion available stays silent with no 404, exactly as before.
     */
    private fun candidates(name: String): List<String> {
        val extension = name.substringAfterLast('.', "")
        if (extension in PLAYABLE) return listOf(name)
        val stem = name.substringBeforeLast('.', name)
        return PLAYABLE.map { "$stem.$it" }
    }

    /**
     * Starts [track], or silences the music channel when this battle has none it can play.
     *
     * **The stop is the point of the `else`.** This used to `return` on an absent or unplayable
     * track, which left the PREVIOUS battle's score running underneath the new one: only 47 of the
     * 502 deployed scenarios have a playable track, so the common transition is exactly the one
     * that took the early exit. `Sound.startMusic` stops what is playing before it starts anything,
     * so a battle that HAS a track was never affected -- which is why the leak was invisible on the
     * scenarios anyone was testing with.
     */
    fun play(track: String?) {
        val url = urlFor(track)
        if (url == null) Sound.stopMusic() else Sound.startMusic(url)
    }

    private fun manifest(): Set<String> {
        available?.let { return it }
        val names =
            try {
                val request = XMLHttpRequest()
                request.open("GET", MANIFEST_URL, false)
                request.send()
                if (request.status.toInt() != 200) {
                    emptySet()
                } else {
                    val parsed = JSON.parse<dynamic>(request.responseText)
                    val length = parsed.length as? Int ?: 0
                    (0 until length).mapNotNull { (parsed[it] as? String)?.lowercase() }.toSet()
                }
            } catch (_: Throwable) {
                emptySet()
            }
        available = names
        return names
    }

    /** Installs a manifest without any network access, for tests. */
    internal fun setManifestForTest(names: Set<String>) {
        available = names.map { it.lowercase() }.toSet()
    }

    internal fun resetForTest() {
        available = null
    }
}
