//Automatically generated by campaing-convert.py
var campaignlist =
[
 {
  "desc": "From the barricades of Republican Spain to the frozen frontier at Lake Khasan, the armoured encirclement at Khalkhin Gol, the life-or-death struggle against Nazi invasion, and the final thunder of the Manchurian Offensive, this campaign follows the Red Army through a decade of transformation. Learn to command tanks, artillery, infantry, and aircraft as an experimental interwar force becomes the vast combined-arms machine that carried the war from the Soviet border to Berlin and then turned east against the Kwantung Army. Every theatre demands a different answer: internationalism in Spain, manoeuvre in Mongolia, endurance in 1941, deep operations in Europe, and speed across Manchuria. Story Mode compresses these campaigns into the long career of one unnamed commander and four recurring fictional composite staff officers; historical people and events remain distinct from that narrative frame.",
  "eqp": "eqp-lxf",
  "file": "camp6bn9.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 0,
  "scenarios": 21,
  "title": "Red Army Campaign (1936-1945)"
 },
 {
  "desc": "Fight where no front line exists. Lead a Soviet partisan formation deep behind German lines, building a fighting force from Red Army stragglers, escaped prisoners, underground organisers, and local volunteers. Ambush convoys, destroy bridges, derail troop trains, evade punitive expeditions, and coordinate your blows with the Red Army’s great offensives. Inspired by the vast “Rail War” and Operation Concert, this is a campaign of concealment, nerve, and ruthless economy: you will rarely have the enemy’s firepower, but you can choose the time, place, and purpose of every attack. Survive the forests, keep the movement alive, and make the occupier fear every kilometre of track.",
  "eqp": "eqp-lxf",
  "file": "camp6bn5.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 288,
  "scenarios": 10,
  "title": "Stay Alive - Red Partisans (1941-1945)"
 },
 {
  "desc": "Begin with scattered rifles in the mountains and end at the head of a national army. Under Josip Broz Tito, the Yugoslav Partisans grew from the 1941 uprising into one of Europe’s most formidable resistance movements, fighting occupation troops, collaborationist forces, and encirclement after encirclement. Cross the Balkan mountains, preserve your wounded through desperate retreats, strike garrisons and railways, and turn liberated territory into the base of a wider people’s war. From the early republics and the ordeals of Neretva and Sutjeska to Belgrade and final liberation, this campaign rewards mobility, political endurance, and the ability to rebuild after apparent disaster.",
  "eqp": "eqp-lxf",
  "file": "camp6bn8.json",
  "flag": 43,
  "deployphase": false,
  "prestige": 168,
  "scenarios": 19,
  "title": "Yugoslav Front (1941-1945)"
 },
 {
  "desc": "Berlin has fallen—but the war has not ended. In this alternate-history epic, the Soviet Union turns its victorious armies westward and tests whether the operational art that shattered the Wehrmacht can overcome the armies of post-war Europe. Command veteran Guards formations, massed armour, artillery, and air power across a continent exhausted by six years of war, where yesterday’s allies become tomorrow’s enemies and every advance stretches the limits of supply. Red Destiny is a grand “what if?” campaign about momentum, escalation, and the price of total victory: carry the red banner beyond Germany, break successive defensive lines, and decide how far the road from Stalingrad can truly run.",
  "eqp": "eqp-lxf",
  "file": "reddestiny.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 700,
  "scenarios": 19,
  "title": "Red Destiny (1946-1954)"
 },
 {
  "desc": "Lead the Korean People’s Army in a war that begins with breathtaking speed and becomes a brutal contest of endurance. Break through the 38th parallel, seize Seoul, and drive south with Soviet-built armour before United Nations forces can establish a stable front. Then face the reversal: the Pusan Perimeter, the shock of Inchon, retreat through shattered communications, Chinese intervention, frozen mountains, and a war of attrition that refuses to end. This campaign follows the Korean War from mobile offensives to entrenched stalemate, forcing you to master tempo, mountain warfare, fragile logistics, and the constant danger of an enemy whose air and naval power can turn every exposed road into a killing ground.",
  "eqp": "eqp-lxf",
  "file": "ncampdfn.json",
  "flag": 25,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 14,
  "title": "North Korea (1950-1953)"
 },
 {
  "desc": "A revolution can be defeated without ending its journey. Follow the German Forty-Eighters from the barricades of 1848, through exile across the Atlantic, and into the ranks of the Union Army during the American Civil War. Inspired by figures such as Franz Sigel, Friedrich Hecker, and Carl Schurz, this unusual campaign links democratic revolution in Europe with the struggle against slavery and secession in the United States. Fight street battles, survive political defeat and emigration, then rebuild your cause in a new land among German-American volunteers. Across two continents and nearly two decades, the campaign turns exile into experience—and experience into a second chance to fight for freedom.",
  "eqp": "eqp-kaiser",
  "file": "aljf.json",
  "flag": 196,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 26,
  "title": "A Long Journey to Freedom (1848-1865)"
 },
 {
  "desc": "In 1919, revolution in Hungary was surrounded by hostile armies and measured in weeks. Command the Hungarian Red Army as Béla Kun’s Soviet Republic fights for survival against Romanian and Czechoslovak intervention, while the old Habsburg order collapses and new borders are imposed by force. Under the gifted chief of staff Aurél Stromfeld, the Northern Campaign briefly drove into Upper Hungary and helped proclaim the Slovak Soviet Republic; in the east, Romanian pressure threatened the road to Budapest itself. This compact campaign is a race against military encirclement, political fracture, and time—an opportunity to preserve a revolution whose historical victories proved as dramatic as they were fleeting.",
  "eqp": "eqp-kaiser",
  "file": "rhu.json",
  "flag": 187,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 10,
  "title": "Hungarian Soviet Republic (1919)"
 },
 {
  "desc": "Mount up with Semyon Budyonny’s First Cavalry Army, the legendary Konarmia, and turn speed into a strategic weapon. Sweep across the plains at Voronezh and Kastornoye, break Denikin’s retreat through Rostov and the Donbas, race west toward Lwów, and return for the final struggle over Crimea. Red cavalry does not fight alone: tachankas, horse artillery, armoured cars, aircraft, and armoured trains transform a mass of sabres into a mobile combined-arms force. This campaign is about reconnaissance, flank attacks, railway junctions, pursuit, and knowing when not to charge. Keep the army moving, shatter the enemy’s rear, and write your own legend beneath the red banner.",
  "eqp": "eqp-kaiser",
  "file": "ccampdfc.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 1500,
  "scenarios": 13,
  "title": "Bolshevik Cavalry (1918-1920)"
 },
 {
  "desc": "The German Empire is collapsing, the fleet is ordered toward a final suicidal battle, and the sailors of Kiel refuse. You are a fictional sailor-delegate elected to Kiel’s revolutionary action committee, entrusted with its first armed column and sent by the councils from one rising city to the next. The campaign compresses several overlapping local uprisings into your journey through Wilhelmshaven and Frankfurt to Berlin: local councils lend you troops, but their political leaders will argue over every priority—prisoners or communications, expansion or consolidation, public legitimacy or control of the state machinery. Can the councils turn mutiny into a new power before the old officer corps and the emerging republic contain the revolution?",
  "eqp": "eqp-kaiser",
  "file": "novemberrevolution.json",
  "flag": 188,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 4,
  "title": "The November Revolution (1918)"
 },
 {
  "desc": "You are a former Imperial officer who has taken the Soviet oath, and for two years you will be outgunned by your own class. Denikin has British rifles, British shells, British tanks and two Entente squadrons in the Black Sea. You have militia who must first be taught to dig, a railway that keeps getting cut, and orders that usually amount to holding something for four more days.<br><br>Nineteen operations from the Don to the Crimea. Close the Don behind the Ice March. Hold Ekaterinodar while Kornilov throws his cadets at it. Walk the Taman columns out along the coast road with the sea on one flank and the mountains on the other. Give ground across the Kuban, the Terek and the Manych as the Moscow Directive rolls north — and note what these missions are actually scored on: the task you are given is the task you are judged on, and a front that bends somewhere else is never called your defeat.<br><br>Then Orel, where the Latvian riflemen and Primakov’s Chervonny Cossacks go in at Kromy against an army that has outrun its own supply and requisitioned away its own recruiting ground — and the arrows on the map finally turn south. Kharkov. The Donbass. A quay at Novorossiysk where an army finds out how many ships the Entente actually sent. And a year later, the Sivash mud at four in the morning, under a wall that could not be taken.<br><br>Lose at Orel and the campaign does not end — it gets harder. Tula, Moscow, Petrograd: each one a last line that hands you straight back to the pursuit if you hold it.",
  "eqp": "eqp-kaiser",
  "file": "volarm.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 19,
  "title": "The Defeat of Denikin (1918-1920)"
 },
 {
  "desc": "You are a staff captain of the old army, seconded in 1917 to the Czechoslovak brigade because you speak enough Czech to be useful. At Zborov you watch seven thousand volunteers take three lines of trenches while a Russian division beside them votes on whether to leave its own — and you work out, standing between the two, which side of your country you are on.<br><br>Eleven operations and nine thousand versts of railway. Hold the Kiev bridges beside the legionnaires while the Germans come up the Dnieper. Keep the junction at Bachmach open for their echelons and yours on the same timetable. Then Chelyabinsk, where a thrown stove leg, a lynching and a telegram ordering a corps disarmed turn allies into enemies in a single afternoon — and from there the war is yours: Samara, the gold vaults at Kazan, and a month later the same city taken back by an army that was rebuilt while it retreated.<br><br>The Omsk rising, where the task is to get people out and not to win. Ufa, where Kolchak's front collapses less from the fighting than from what he restored behind it. Chita and the ataman's armoured trains. And a quay at Vladivostok in 1920 where the regiment that held the Kiev bridges with you is waiting for a ship home, and there is too much between you to shake hands.<br><br>One hero, one core, and an allegiance that changes exactly once — in a trench in Galicia, before a shot is fired in the civil war.",
  "eqp": "eqp-kaiser",
  "file": "acampdf2.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 350,
  "scenarios": 11,
  "title": "The Legion and the Revolution (1917-1920)"
 },
 {
  "desc": "Twenty months on the Western Front, and only four of them going forward. You begin in April 1919 with a screen instead of an army — a half-strength brigade and four towns on a railway — because every division the Republic owns is committed against Denikin and Kolchak, and the orders from Moscow begin with the word nevertheless.<br><br>Eleven operations from the Lithuanian forests to a frontier post outside Minsk. Delay the advance on Wilno and get the city's Soviet out. Hold the Berezina junctions long enough for the 16th Army to arrive on the river as an army. Sit out January in the fortified line at Dyneburg at minus twenty-five. Then the blow towards Kiev, the crossings held while the 12th Army goes over the Dnieper, and — in June — the Konarmia into the seam at Samhorodok and a Polish front that comes apart because of what it restored behind itself.<br><br>Then Warsaw, where the task is explicitly not to take the city: two offensives on divergent axes with one army's supply had already settled that in July. Bring the divisional cores out east of the Bug. Break the Konarmia out of the pocket at Komarow. Hold the Niemen while a peace conference draws its line on the map your battalions are standing on.<br><br>Note how these missions are scored: the task you are given is the task you are judged on, and a front that gives ground for reasons on somebody else's sector is never called your defeat.",
  "eqp": "eqp-kaiser",
  "file": "polsov.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 11,
  "title": "The Polish-Soviet War (1919-1920)"
 },
 {
  "desc": "Defend the Spanish Republic in the first great anti-fascist war of Europe. Forge scattered militias into the Ejército Popular, hold Madrid against siege, fight beside the International Brigades at Jarama and Guadalajara, and commit your best formations to the desperate battles of Teruel and the Ebro. German and Italian intervention gives Franco’s armies modern aircraft, armour, and experienced troops; the Republic must survive with limited foreign aid, fierce internal disagreements, and volunteers drawn from across the world. Commanders such as José Miaja, Juan Modesto, and Enrique Líster turned improvised columns into a field army. Your task is harder still: preserve that army long enough to win.",
  "eqp": "eqp-gce",
  "file": "gce.json",
  "flag": 226,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 12,
  "title": "Ejercito Popular (1936-1939)"
 },
 {
  "desc": "Follow Georgy Zhukov from the Mongolian steppe to the ruins of Berlin. At Khalkhin Gol, massed armour, artillery, and aircraft encircle the Japanese forces and announce the arrival of a commander who will shape the coming world war. Then confront the German invasion: defend Moscow, help forge the encirclement at Stalingrad, smash successive offensives, and coordinate the overwhelming blows that carry Soviet armies across Eastern Europe. Zhukov’s reputation was built on preparation, concentration, reserves, and a relentless demand for results—often at terrible cost. Across seventeen operations, this campaign offers a commander’s-eye view of the Red Army’s transformation into the force that captured the Reichstag.",
  "eqp": "eqp-comww2",
  "file": "ga4.json",
  "flag": 89,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 17,
  "title": "Zhukov: Red God of War (1939-1945)"
 },
 {
  "desc": "Break out of the gladiator school at Capua and turn a handful of fugitives into the greatest slave uprising Rome ever faced. As Spartacus, Crixus, Gannicus, and thousands of escaped slaves rally beneath a common cause, defeat local militias, seize Roman weapons, cross the Italian mountains, and outmanoeuvre armies that grow more dangerous with every victory. The Senate’s contempt gives way to fear; consular forces fail, and Marcus Licinius Crassus raises eight legions to destroy the revolt. History ends in defeat and crucifixion along the Appian Way. This campaign asks whether discipline, mobility, and unity can give the enslaved a different fate.",
  "eqp": "eqp-ag",
  "file": "spa.json",
  "flag": 310,
  "deployphase": false,
  "prestige": 10,
  "scenarios": 19,
  "title": "Spartacus: The Slave Revolt (73-71 BC)"
 },
 {
  "desc": "Fight a war in which control of a village, a trail, or a tunnel complex can matter more than possession of a capital. Lead the National Liberation Front through the jungles and rice fields of South Vietnam against the armed forces of Saigon and the enormous firepower of the United States. Build hidden bases, ambush patrols, cut roads, survive search-and-destroy operations, and use the Ho Chi Minh trail to replace losses the enemy believes are decisive. From local guerrilla actions to the nationwide shock of the Tet Offensive and the final collapse of South Vietnam, this campaign rewards patience, concealment, political endurance, and the ability to turn tactical survival into strategic victory.",
  "eqp": "eqp-olgcw",
  "file": "nvc.json",
  "flag": 276,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 12,
  "title": "Viet Cong (1964-1975)"
 },
 {
  "desc": "Command the Soviet Black Sea Fleet in a war fought simultaneously at sea, in the air, and along a collapsing coastline. Support the defence of Odessa and Sevastopol, escort transports under Luftwaffe attack, land naval infantry behind enemy lines, hunt Axis shipping with submarines and torpedo craft, and preserve major warships whose bases and repair yards are steadily lost. Admirals Filipp Oktyabrsky and Lev Vladimirsky faced an enemy whose surface fleet was weaker but whose aircraft, mines, and coastal advances made every sortie dangerous. Across twenty-seven operations, the fleet becomes a lifeline, artillery reserve, evacuation force, and spearhead for the return to Crimea.",
  "eqp": "eqp-basekorp",
  "file": "rcampdfr.json",
  "flag": 61,
  "deployphase": true,
  "prestige": 500,
  "scenarios": 27,
  "title": "Soviet Black Sea Fleet (1941-1944)"
 },
 {
  "desc": "Lead the Chinese Red Army through twenty-two years in which survival itself becomes a form of victory. Begin amid the rural uprisings and encirclement campaigns of the late 1920s, escape annihilation on the Long March, and rebuild around Yan’an under Mao Zedong and Zhu De. Then fight the Japanese invasion while preserving the strength needed for the renewed civil war against Chiang Kai-shek’s Nationalists. Guerrilla bases, mountain marches, political mobilisation, and captured weapons gradually give way to large field armies and decisive campaigns. From scattered soviets to the proclamation of the People’s Republic in 1949, this is a campaign about endurance becoming power.",
  "eqp": "eqp-olgww2",
  "file": "rsoc.json",
  "flag": 21,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 19,
  "title": "Red Star Over China (1927-1949)"
 },
 {
  "desc": "Take command of a Soviet Guards Tank Corps and experience deep battle as it was meant to be fought: artillery and aviation rupture the tactical front, mobile formations pour through the breach, and fresh reserves strike into the enemy’s operational rear before a new defence can form. Beginning in the hard campaigns of 1942, build a veteran core of T-34s, motorised infantry, self-propelled guns, engineers, and Guards units capable of surviving repeated breakthrough battles. Prestige is generous enough to create a historically powerful combined-arms force—but losses, fuel, and timing still matter. Drive the corps west through successive offensives until the final approach to Berlin.\n\nCampaign Designer: RC (Bob C)\r\nPlaytesters: Shikaka, Jan Hedstrom, Ze \"JRM\" Carneiro, Dirk Oberlin and Drag D",
  "eqp": "eqp-adlerkorps",
  "file": "062d.json",
  "flag": 61,
  "prestige": 4000,
  "scenarios": 20,
  "title": "The Great Patriotic War USSR Campaign (1942-1945)"
 },
 {
  "desc": "Assume the role of Marshal Georgy Zhukov at the moment the strategic tide begins to turn. Encircle the Axis armies at Stalingrad in Operation Uranus, expand the catastrophe through Saturn, recover Rostov and the Black Sea coast, and fight through Kharkov, Kanev, Kiev, Odessa, Sevastopol, and the long road to the Reichstag. Twenty-seven operations test your ability to absorb counterstrokes, rebuild exhausted armies, mass artillery, and commit armour at the decisive point. History ends in Berlin—but this campaign does not. After the fall of the Third Reich, an alternate path carries the offensive across Western Europe, Britain, and ultimately the Atlantic. Can victory become world revolution?",
  "eqp": "eqp-adlerkorps",
  "file": "camp6.json",
  "flag": 61,
  "prestige": 500,
  "scenarios": 27,
  "title": "Soviet Counter-Offensive Campaign (1942-1946)"
 },
 {
  "desc": "From the Italian invasion of 1940 and the mountain resistance against the Wehrmacht to the civil war of 1943-49. Partway through, the campaign asks you to choose your side: the Hellenic Army of the Greek government, or the Communist Party's ELAS/Democratic Army. From the LXF efile (camp6bn4).",
  "eqp": "eqp-lxf",
  "file": "camp6bn4.json",
  "flag": 39,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 29,
  "title": "Greece: Resistance and Civil War (1940-1949)"
 },
 {
  "desc": "A Soviet World War 2 campaign from 1939 to 1945, from the Atomic efile (forward).",
  "eqp": "eqp-atomic",
  "file": "forward.json",
  "flag": 89,
  "deployphase": true,
  "prestige": 2300,
  "scenarios": 44,
  "title": "Forward, Comrade! (1939-1945)"
 },
 {
  "desc": "Command on the Eastern Front, from the Volga to Lake Baikal. The Czechoslovak revolt and the Komuch have taken Samara and Kazan; Kolchak follows them, and behind him stand British rifles, the Siberian Cossacks and the whole Trans-Siberian Railway. Hold the Volga towns through the summer of 1918, survive Kolchak’s spring offensive in the Urals, and then turn the war around at Belebei and Ufa — across the passes, over the Tobol, into Siberia, and on to Irkutsk. Every early episode is a defence measured in time bought and formations kept intact, not ground held; when the initiative changes hands, so do the objectives. A bad result at Chistopol opens an emergency line of battles back towards Moscow, and any success on it returns you at once to the counteroffensive. The title is the enemy’s own motto, taken off his banner.",
  "eqp": "eqp-kaiser",
  "file": "simpob.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 25,
  "title": "Sim Pobedishi! - The Red East (1918-1920)"
 }
]
