//Automatically generated by campaing-convert.py
var campaignlist =
[
 {
  "desc": "From the barricades of Republican Spain to the frozen frontier at Lake Khasan, the armoured encirclement at Khalkhin Gol, the life-or-death struggle against Nazi invasion, and the final thunder of the Manchurian Offensive, this campaign follows the Red Army through a decade of transformation. Learn to command tanks, artillery, infantry, and aircraft as an experimental interwar force becomes the vast combined-arms machine that carried the war from the Soviet border to Berlin and then turned east against the Kwantung Army. Every theatre demands a different answer: internationalism in Spain, manoeuvre in Mongolia, endurance in 1941, deep operations in Europe, and speed across Manchuria.",
  "eqp": "eqp-lxf",
  "file": "camp6bn9.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 0,
  "scenarios": 21,
  "title": "Red Army Campaign (1936-1945)"
 },
 {
  "desc": "Fight where no front line exists. Lead a Soviet partisan formation deep behind German lines, building a fighting force from Red Army stragglers, escaped prisoners, underground organisers, and local volunteers. Ambush convoys, destroy bridges, derail troop trains, evade punitive expeditions, and coordinate your blows with the Red Army’s great offensives. Inspired by the vast “Rail War” and Operation Concert, this is a campaign of concealment, nerve, and ruthless economy: you will rarely have the enemy’s firepower, but you can choose the time, place, and purpose of every attack. Survive the forests, keep the movement alive, and make the occupier fear every kilometre of track.",
  "eqp": "eqp-lxf",
  "file": "camp6bn5.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 288,
  "scenarios": 10,
  "title": "Stay Alive - Red Partisans (1941-1945)"
 },
 {
  "desc": "Begin with scattered rifles in the mountains and end at the head of a national army. Under Josip Broz Tito, the Yugoslav Partisans grew from the 1941 uprising into one of Europe’s most formidable resistance movements, fighting occupation troops, collaborationist forces, and encirclement after encirclement. Cross the Balkan mountains, preserve your wounded through desperate retreats, strike garrisons and railways, and turn liberated territory into the base of a wider people’s war. From the early republics and the ordeals of Neretva and Sutjeska to Belgrade and final liberation, this campaign rewards mobility, political endurance, and the ability to rebuild after apparent disaster.",
  "eqp": "eqp-lxf",
  "file": "camp6bn8.json",
  "flag": 43,
  "deployphase": false,
  "prestige": 168,
  "scenarios": 19,
  "title": "Yugoslav Front (1941-1945)"
 },
 {
  "desc": "Berlin has fallen—but the war has not ended. In this alternate-history epic, the Soviet Union turns its victorious armies westward and tests whether the operational art that shattered the Wehrmacht can overcome the armies of post-war Europe. Command veteran Guards formations, massed armour, artillery, and air power across a continent exhausted by six years of war, where yesterday’s allies become tomorrow’s enemies and every advance stretches the limits of supply. Red Destiny is a grand “what if?” campaign about momentum, escalation, and the price of total victory: carry the red banner beyond Germany, break successive defensive lines, and decide how far the road from Stalingrad can truly run.",
  "eqp": "eqp-lxf",
  "file": "reddestiny.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 700,
  "scenarios": 19,
  "title": "Red Destiny (1946-1954)"
 },
 {
  "desc": "Lead the Korean People’s Army in a war that begins with breathtaking speed and becomes a brutal contest of endurance. Break through the 38th parallel, seize Seoul, and drive south with Soviet-built armour before United Nations forces can establish a stable front. Then face the reversal: the Pusan Perimeter, the shock of Inchon, retreat through shattered communications, Chinese intervention, frozen mountains, and a war of attrition that refuses to end. This campaign follows the Korean War from mobile offensives to entrenched stalemate, forcing you to master tempo, mountain warfare, fragile logistics, and the constant danger of an enemy whose air and naval power can turn every exposed road into a killing ground.",
  "eqp": "eqp-lxf",
  "file": "ncampdfn.json",
  "flag": 25,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 14,
  "title": "North Korea (1950-1953)"
 },
 {
  "desc": "A revolution can be defeated without ending its journey. Follow the German Forty-Eighters from the barricades of 1848, through exile across the Atlantic, and into the ranks of the Union Army during the American Civil War. Inspired by figures such as Franz Sigel, Friedrich Hecker, and Carl Schurz, this unusual campaign links democratic revolution in Europe with the struggle against slavery and secession in the United States. Fight street battles, survive political defeat and emigration, then rebuild your cause in a new land among German-American volunteers. Across two continents and nearly two decades, the campaign turns exile into experience—and experience into a second chance to fight for freedom.",
  "eqp": "eqp-kaiser",
  "file": "aljf.json",
  "flag": 196,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 26,
  "title": "A Long Journey to Freedom (1848-1865)"
 },
 {
  "desc": "In 1919, revolution in Hungary was surrounded by hostile armies and measured in weeks. Command the Hungarian Red Army as Béla Kun’s Soviet Republic fights for survival against Romanian and Czechoslovak intervention, while the old Habsburg order collapses and new borders are imposed by force. Under the gifted chief of staff Aurél Stromfeld, the Northern Campaign briefly drove into Upper Hungary and helped proclaim the Slovak Soviet Republic; in the east, Romanian pressure threatened the road to Budapest itself. This compact campaign is a race against military encirclement, political fracture, and time—an opportunity to preserve a revolution whose historical victories proved as dramatic as they were fleeting.",
  "eqp": "eqp-kaiser",
  "file": "rhu.json",
  "flag": 187,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 10,
  "title": "Hungarian Soviet Republic (1919)"
 },
 {
  "desc": "Mount up with Semyon Budyonny’s First Cavalry Army, the legendary Konarmia, and turn speed into a strategic weapon. Sweep across the plains at Voronezh and Kastornoye, break Denikin’s retreat through Rostov and the Donbas, race west toward Lwów, and return for the final struggle over Crimea. Red cavalry does not fight alone: tachankas, horse artillery, armoured cars, aircraft, and armoured trains transform a mass of sabres into a mobile combined-arms force. This campaign is about reconnaissance, flank attacks, railway junctions, pursuit, and knowing when not to charge. Keep the army moving, shatter the enemy’s rear, and write your own legend beneath the red banner.",
  "eqp": "eqp-kaiser",
  "file": "ccampdfc.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 1500,
  "scenarios": 13,
  "title": "Bolshevik Cavalry (1918-1920)"
 },
 {
  "desc": "The German Empire is collapsing, the fleet is ordered toward a final suicidal battle, and the sailors of Kiel refuse. From mutiny in the naval bases to workers’ and soldiers’ councils across the country, the November Revolution reaches Berlin and brings down the Kaiser in a matter of days. Command revolutionary sailors, armed workers, and defecting soldiers through a compact campaign of seized arsenals, occupied stations, street fighting, and political uncertainty. Rosa Luxemburg and Karl Liebknecht stand for a more radical future, while the old officer corps and the Freikorps prepare their answer. Can the councils survive the birth of the republic—or will the revolution be contained and crushed?",
  "eqp": "eqp-kaiser",
  "file": "novemberrevolution.json",
  "flag": 188,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 4,
  "title": "The November Revolution (1918)"
 },
 {
  "desc": "Stand between Anton Denikin’s Volunteer Army and the road to Moscow. This long southern campaign begins amid the White movement’s Ice March and rise in the Kuban, passes through the battles for Tsaritsyn and the Don, and reaches its decisive crisis at Orel, where the Red Southern Front finally seizes the strategic initiative. Counterattack through Kursk, Kharkov, the Donbas, Rostov, and the North Caucasus as White armies, Cossack cavalry, tanks, and armoured trains retreat toward the Black Sea. The campaign ends at Novorossiysk, where Denikin’s defeated forces scramble to evacuate. Recover from early reverses, concentrate reserves, and turn defence into relentless pursuit.",
  "eqp": "eqp-kaiser",
  "file": "volarm.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 19,
  "title": "The Defeat of Denikin (1918-1920)"
 },
 {
  "desc": "Begin at Zborov, where Czechoslovak volunteers fight Austria-Hungary for the promise of national independence, and then embark on one of the strangest military odysseys of the twentieth century. After the Russian Revolution and Brest-Litovsk, the Legion’s route home runs not west but thousands of kilometres east along the Trans-Siberian Railway. Command legionnaires, captured artillery, and famous armoured trains through Chelyabinsk, the Volga, Siberian stations, Lake Baikal, and the long withdrawal to Vladivostok. Surrounded by civil war and shifting alliances, you must control the rails, preserve the force, and keep moving until an army trapped inside Russia can finally reach the sea.",
  "eqp": "eqp-kaiser",
  "file": "acampdf2.json",
  "flag": 144,
  "deployphase": false,
  "prestige": 350,
  "scenarios": 11,
  "title": "Czech Legion - Siberian Anabasis (1917-1920)"
 },
 {
  "desc": "The road west appears open. After the Polish advance on Kiev, the Red Army counterattacks under Mikhail Tukhachevsky, drives through Belarus, and approaches Warsaw with the promise of carrying revolution into Europe. To the south, Budyonny’s First Cavalry Army battles toward Lwów while the front stretches and supplies fall behind. History ends with the “Miracle on the Vistula,” a Polish counterstroke that shatters the Soviet offensive—but this campaign places the decision in your hands. Balance speed against logistics, coordinate distant fronts, break fortified river lines, and decide whether the red advance will collapse outside Warsaw or change the political future of the continent.",
  "eqp": "eqp-kaiser",
  "file": "polsov.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 11,
  "title": "The Polish-Soviet War: The Red Advance (1919-1920)"
 },
 {
  "desc": "Defend the Spanish Republic in the first great anti-fascist war of Europe. Forge scattered militias into the Ejército Popular, hold Madrid against siege, fight beside the International Brigades at Jarama and Guadalajara, and commit your best formations to the desperate battles of Teruel and the Ebro. German and Italian intervention gives Franco’s armies modern aircraft, armour, and experienced troops; the Republic must survive with limited foreign aid, fierce internal disagreements, and volunteers drawn from across the world. Commanders such as José Miaja, Juan Modesto, and Enrique Líster turned improvised columns into a field army. Your task is harder still: preserve that army long enough to win.",
  "eqp": "eqp-gce",
  "file": "gce.json",
  "flag": 226,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 12,
  "title": "Ejercito Popular (1936-1939)"
 },
 {
  "desc": "Follow Georgy Zhukov from the Mongolian steppe to the ruins of Berlin. At Khalkhin Gol, massed armour, artillery, and aircraft encircle the Japanese forces and announce the arrival of a commander who will shape the coming world war. Then confront the German invasion: defend Moscow, help forge the encirclement at Stalingrad, smash successive offensives, and coordinate the overwhelming blows that carry Soviet armies across Eastern Europe. Zhukov’s reputation was built on preparation, concentration, reserves, and a relentless demand for results—often at terrible cost. Across seventeen operations, this campaign offers a commander’s-eye view of the Red Army’s transformation into the force that captured the Reichstag.",
  "eqp": "eqp-comww2",
  "file": "ga4.json",
  "flag": 89,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 17,
  "title": "Zhukov: Red God of War (1939-1945)"
 },
 {
  "desc": "Break out of the gladiator school at Capua and turn a handful of fugitives into the greatest slave uprising Rome ever faced. As Spartacus, Crixus, Gannicus, and thousands of escaped slaves rally beneath a common cause, defeat local militias, seize Roman weapons, cross the Italian mountains, and outmanoeuvre armies that grow more dangerous with every victory. The Senate’s contempt gives way to fear; consular forces fail, and Marcus Licinius Crassus raises eight legions to destroy the revolt. History ends in defeat and crucifixion along the Appian Way. This campaign asks whether discipline, mobility, and unity can give the enslaved a different fate.",
  "eqp": "eqp-ag",
  "file": "spa.json",
  "flag": 310,
  "deployphase": false,
  "prestige": 10,
  "scenarios": 19,
  "title": "Spartacus: The Slave Revolt (73-71 BC)"
 },
 {
  "desc": "Fight a war in which control of a village, a trail, or a tunnel complex can matter more than possession of a capital. Lead the National Liberation Front through the jungles and rice fields of South Vietnam against the armed forces of Saigon and the enormous firepower of the United States. Build hidden bases, ambush patrols, cut roads, survive search-and-destroy operations, and use the Ho Chi Minh trail to replace losses the enemy believes are decisive. From local guerrilla actions to the nationwide shock of the Tet Offensive and the final collapse of South Vietnam, this campaign rewards patience, concealment, political endurance, and the ability to turn tactical survival into strategic victory.",
  "eqp": "eqp-olgcw",
  "file": "nvc.json",
  "flag": 276,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 12,
  "title": "Viet Cong (1964-1975)"
 },
 {
  "desc": "Command the Soviet Black Sea Fleet in a war fought simultaneously at sea, in the air, and along a collapsing coastline. Support the defence of Odessa and Sevastopol, escort transports under Luftwaffe attack, land naval infantry behind enemy lines, hunt Axis shipping with submarines and torpedo craft, and preserve major warships whose bases and repair yards are steadily lost. Admirals Filipp Oktyabrsky and Lev Vladimirsky faced an enemy whose surface fleet was weaker but whose aircraft, mines, and coastal advances made every sortie dangerous. Across twenty-seven operations, the fleet becomes a lifeline, artillery reserve, evacuation force, and spearhead for the return to Crimea.",
  "eqp": "eqp-basekorp",
  "file": "rcampdfr.json",
  "flag": 61,
  "deployphase": true,
  "prestige": 500,
  "scenarios": 27,
  "title": "Soviet Black Sea Fleet (1941-1944)"
 },
 {
  "desc": "Lead the Chinese Red Army through twenty-two years in which survival itself becomes a form of victory. Begin amid the rural uprisings and encirclement campaigns of the late 1920s, escape annihilation on the Long March, and rebuild around Yan’an under Mao Zedong and Zhu De. Then fight the Japanese invasion while preserving the strength needed for the renewed civil war against Chiang Kai-shek’s Nationalists. Guerrilla bases, mountain marches, political mobilisation, and captured weapons gradually give way to large field armies and decisive campaigns. From scattered soviets to the proclamation of the People’s Republic in 1949, this is a campaign about endurance becoming power.",
  "eqp": "eqp-olgww2",
  "file": "rsoc.json",
  "flag": 21,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 19,
  "title": "Red Star Over China (1927-1949)"
 },
 {
  "desc": "Take command of a Soviet Guards Tank Corps and experience deep battle as it was meant to be fought: artillery and aviation rupture the tactical front, mobile formations pour through the breach, and fresh reserves strike into the enemy’s operational rear before a new defence can form. Beginning in the hard campaigns of 1942, build a veteran core of T-34s, motorised infantry, self-propelled guns, engineers, and Guards units capable of surviving repeated breakthrough battles. Prestige is generous enough to create a historically powerful combined-arms force—but losses, fuel, and timing still matter. Drive the corps west through successive offensives until the final approach to Berlin.\n\nCampaign Designer: RC (Bob C)\r\nPlaytesters: Shikaka, Jan Hedstrom, Ze \"JRM\" Carneiro, Dirk Oberlin and Drag D",
  "eqp": "eqp-adlerkorps",
  "file": "062d.json",
  "flag": 61,
  "prestige": 4000,
  "scenarios": 20,
  "title": "The Great Patriotic War USSR Campaign (1942-1945)"
 },
 {
  "desc": "Assume the role of Marshal Georgy Zhukov at the moment the strategic tide begins to turn. Encircle the Axis armies at Stalingrad in Operation Uranus, expand the catastrophe through Saturn, recover Rostov and the Black Sea coast, and fight through Kharkov, Kanev, Kiev, Odessa, Sevastopol, and the long road to the Reichstag. Twenty-seven operations test your ability to absorb counterstrokes, rebuild exhausted armies, mass artillery, and commit armour at the decisive point. History ends in Berlin—but this campaign does not. After the fall of the Third Reich, an alternate path carries the offensive across Western Europe, Britain, and ultimately the Atlantic. Can victory become world revolution?\n\nOriginal Author: Tim Ruger\r\n",
  "eqp": "eqp-adlerkorps",
  "file": "camp6.json",
  "flag": 61,
  "prestige": 500,
  "scenarios": 27,
  "title": "Soviet Counter-Offensive Campaign (1942-1946)"
 },
 {
  "desc": "From the Italian invasion of 1940 and the mountain resistance against the Wehrmacht to the civil war of 1943-49. Partway through, the campaign asks you to choose your side: the Hellenic Army of the Greek government, or the Communist Party's ELAS/Democratic Army. From the LXF efile (camp6bn4).",
  "eqp": "eqp-lxf",
  "file": "camp6bn4.json",
  "flag": 39,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 29,
  "title": "Greece: Resistance and Civil War (1940-1949)"
 },
 {
  "desc": "A Soviet World War 2 campaign from 1939 to 1945, from the Atomic efile (forward).",
  "eqp": "eqp-atomic",
  "file": "forward.json",
  "flag": 89,
  "deployphase": true,
  "prestige": 2300,
  "scenarios": 44,
  "title": "Forward, Comrade! (1939-1945)"
 },
 {
  "desc": "The Russian Civil War in the East, from the Volga to Vladivostok, from the Kaiser efile (simpob) — flipped to play the Red side against the anti-Bolshevik forces.",
  "eqp": "eqp-kaiser",
  "file": "simpob.json",
  "flag": 100,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 25,
  "title": "Sim Pobedishi! - The Red East (1918-1920)"
 }
]
