//Automatically generated by campaing-convert.py
var campaignlist =
[
 {
  "desc": "Seseña, October 1936: Soviet tanks go into action for the first time, on the dusty approaches to Madrid. Nine years and twenty-one battles later, the same career ends on the Manchurian frontier. In between lie Lake Khasan and Khalkhin Gol, the ice of the Raate Road, the catastrophe at Białystok–Minsk, the winter counterblow before Moscow, the Tatsinskaya raid, Kursk, Belgrade, Balaton and the road to Vienna.\n\nThis is the Red Army's decade of apprenticeship, and every new war punishes the habits the last one taught. In Story Mode, a staff of recurring officers argues over the map before each operation, and the briefings end in hard bargains: push the timetable for prestige and hardened troops, or spend it on fuel, shells and a reserve against the counterstroke.",
  "eqp": "eqp-lxf",
  "file": "camp6bn9.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 0,
  "scenarios": 21,
  "title": "Red Army Campaign (1936-1945)"
 },
 {
  "desc": "No front line. No relief column. No second chance. Your orders read like a thriller: strike the battleship Tirpitz at anchor with a commando raid. Get a stranded American politician through a captured port to a British submarine waiting offshore. Knock out two Luftwaffe airfields so that a hidden German railway gun called Bruno can finally be hunted down.\n\nTen missions take a Soviet partisan command from the rearguard fighting of 1941 through the forests of the Baltic and Belarus to the Narva breakthrough, and finally into Manchuria in August 1945. You will almost never have the numbers. Strike where the enemy feels safe, split your force when the plan demands it, and vanish before the punitive columns arrive. The title is not a slogan. It is the brief.",
  "eqp": "eqp-lxf",
  "file": "camp6bn5.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 288,
  "scenarios": 10,
  "title": "Stay Alive - Red Partisans (1941-1945)"
 },
 {
  "desc": "Summer 1941. The kingdom has fallen in eleven days, and in the Mačva a few hundred fighters decide the occupation will not be a quiet one. Take the Partisans from the uprising at Bela Crkva and the betrayal at Užice into the great offensives meant to annihilate them: Case White on the Neretva, Case Black on the Sutjeska, and German paratroopers dropping on Tito's headquarters at Drvar.\n\nNineteen battles turn a guerrilla band into an army corps. Rail raids and hit-and-run strikes give way to Belgrade, Knin, Mostar, Sarajevo and the race for Trieste, and even after Germany surrenders, one last Axis column in Slovenia refuses to lay down its arms. The mountains made this army. Now it must come down from them and win.",
  "eqp": "eqp-lxf",
  "file": "camp6bn8.json",
  "flag": 43,
  "deployphase": false,
  "prestige": 168,
  "scenarios": 19,
  "title": "Yugoslav Front (1941-1945)"
 },
 {
  "desc": "Comrade General, the Party regrets to inform you that the war is not over. In this alternate history, you crush a Polish rising at Białystok, storm the Seelow Heights and find British volunteers waiting in the ruins of Berlin. The road west is open, and Moscow intends to follow it to the sea and beyond.\n\nYour own performance decides where the Party sends you next. Take Berlin brilliantly and you are rushed to the Chinese frontier; win it cleanly and you are offered a \"tour\" of Italy; scrape through and it is Greece and Crete. Every path meets again in the Low Countries, the Ardennes and at Dunkirk, where you are judged once more: a masterstroke opens the Channel at once, anything less means years of chasing the Allies through France to Gibraltar and back to a Ukraine in revolt. At the end of both roads, London is waiting.",
  "eqp": "eqp-lxf",
  "file": "reddestiny.json",
  "flag": 19,
  "deployphase": false,
  "prestige": 700,
  "scenarios": 19,
  "title": "Red Destiny (1946-1954)"
 },
 {
  "desc": "Dawn, 25 June 1950. Soviet-built tanks cross the 38th parallel, Seoul falls in days, and within weeks the Korean People's Army is hammering at the Pusan perimeter. One more push and the whole peninsula is yours. Then the enemy lands behind you, and the pursuer becomes the hunted.\n\nFourteen battles follow the war through every violent reversal: a last stand short of the Yalu, a flight behind enemy lines to lead cut-off partisans at Majon-ni, the Chinese intervention, the deep raid on Wonju and the great spring offensives of 1951. The enemy owns the sky. Every road in daylight is a gamble, and every hill is a place to hide an army.",
  "eqp": "eqp-lxf",
  "file": "ncampdfn.json",
  "flag": 25,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 14,
  "title": "North Korea (1950-1953)"
 },
 {
  "desc": "\"Lieber Freund, not much time to write...\" So begins a correspondence that will span two continents and seventeen years. Its author takes up a rifle for the German revolution of 1848, marches with Hecker's volunteers and the Palatinate insurgents, and watches the Prussian army crush every hope at Waghäusel.\n\nExile is not the end of the story. In America, the Forty-Eighters take up arms again, this time for the Union and against slavery. Seize the St. Louis Arsenal, win Missouri, then follow the letters through Pea Ridge, Fredericksburg, Vicksburg and Gettysburg, down to Mobile Bay and on to a final assault on Richmond. Twenty-six battles, one lifelong cause: the revolution lost in Baden may yet be won in Virginia.",
  "eqp": "eqp-kaiser",
  "file": "aljf.json",
  "flag": 196,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 26,
  "title": "A Long Journey to Freedom (1848-1865)"
 },
 {
  "desc": "Spring 1919. Budapest has proclaimed a Soviet republic, and the armies of its neighbours are already on the march. You are the commissar sent to the front: first to break out of the trap at Zilah, then to hold the Tisza bridgehead at Szolnok while the capital holds its breath.\n\nThen the Hungarian Red Army does the impossible. Tens of thousands of factory workers march north, Miskolc and Kassa fall, and the offensive reaches the Polish border at Bártfa. But every triumph is borrowed time, and in July the republic stakes everything on a last throw across the Tisza. Between battles, commanders and people's commissars clash over what the revolution can afford, and your decisions shape the army that fights for its survival.",
  "eqp": "eqp-kaiser",
  "file": "rhu.json",
  "flag": 187,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 10,
  "title": "Hungarian Soviet Republic (1919)"
 },
 {
  "desc": "\"Comrade Commander! Come quickly, we must act swiftly.\" Your political commissar has arrived at Voronezh with orders from Moscow, and the Red cavalry mounts up. Ahead lies a year in the saddle: the drive on Rostov, the long ride to the Polish front, the breakthrough at Brody and the gallop towards Lwów.\n\nThen the horsemen are caught. At Komarów, in the last great cavalry battle, the trap closes around you; at Kakhovka and Perekop, the war against Wrangel becomes a war of wire and trenches that no charge can leap. Thirteen battles from Voronezh to Sevastopol ask one question: can you tell the moment for sabres from the moment for machine-gun carts, horse artillery and armoured trains?",
  "eqp": "eqp-kaiser",
  "file": "ccampdfc.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 1500,
  "scenarios": 13,
  "title": "Bolshevik Cavalry (1918-1920)"
 },
 {
  "desc": "November 1918. The admirals order the High Seas Fleet out for one last death ride. In Kiel, the sailors refuse and elect you to lead them. Four battles carry the uprising from the naval base to Wilhelmshaven, Frankfurt and finally Berlin, where the Kaiser has ordered a Jäger regiment into a burning capital.\n\nThis is a revolution run by committee, and the committee never stops arguing. Free the prisoners or seize the telegraph? Take the town hall or the barracks? Spread the uprising or secure what you already hold? Every decision changes the forces the councils lend you. A monarchy can fall in a week, if you are the one who makes it fall.",
  "eqp": "eqp-kaiser",
  "file": "novemberrevolution.json",
  "flag": 188,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 4,
  "title": "The November Revolution (1918)"
 },
 {
  "desc": "You are a former Imperial officer who has taken the Soviet oath, and for two years you will be outgunned by your own class. Denikin has British rifles, British shells, British tanks and Entente squadrons in the Black Sea. You have militia who must first be taught to dig, a railway that keeps getting cut, and orders that usually amount to holding something for four more days.\n\nNineteen operations from the Don to the Crimea. Shut the Don crossings behind the Ice March. Hold Ekaterinodar while Kornilov throws his cadets at it. Walk the Taman columns out along the coast road with the sea on one flank and the mountains on the other. Give ground across the Kuban, the Terek and the Manych as the Moscow Directive rolls north, and remember that you are judged on the task you were given, not on a front that bends somewhere else.\n\nThen Orel, where the Latvian riflemen and Primakov's Chervonny Cossacks go in at Kromy and the arrows on the map finally turn south. Kharkov. A quay at Novorossiysk, where a beaten army learns how many ships the Entente actually sent. And a year later, the Sivash mud in the dark, under a wall that was never supposed to fall.\n\nLose at Orel and the campaign does not end: it gets harder. Tula, Moscow, even Petrograd against Yudenich: each one a last line, and holding any of them hands you straight back to the pursuit.",
  "eqp": "eqp-kaiser",
  "file": "volarm.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 19,
  "title": "The Defeat of Denikin (1918-1920)"
 },
 {
  "desc": "July 1917. You are a staff captain of the old army, attached to the Czechoslovak brigade because you speak enough Czech to be useful. At Zborov you watch volunteers storm three lines of trenches while a Russian division beside them votes on whether to leave its own, and somewhere between the two, you choose your side.\n\nEleven operations and nine thousand versts of railway follow. Hold the Kiev bridges beside the legionnaires and keep Bakhmach open for their trains, then watch a thrown stove leg at Chelyabinsk turn allies into enemies in a single afternoon. Fight for Samara and the gold of Kazan, get people out of Omsk alive, and push east against Kolchak and the ataman's armoured trains. On a quay at Vladivostok in 1920, the men who once held the bridges with you are waiting for a ship home, and there is too much between you to shake hands.",
  "eqp": "eqp-kaiser",
  "file": "acampdf2.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 350,
  "scenarios": 11,
  "title": "The Legion and the Revolution (1917-1920)"
 },
 {
  "desc": "April 1919. Every division the Republic owns is fighting Denikin and Kolchak, so the Western Front gets a half-strength brigade, four towns on a railway and orders that begin with the word \"nevertheless\". Your war against Poland starts with too little of everything, and for most of its long months it goes backwards.\n\nDelay the advance on Wilno, hold the Berezina, sit out the Latgale winter at minus twenty-five. Then the Konarmia tears open the Polish front, and the whole army surges west towards Warsaw, straight into disaster. Bring the divisions back across the Bug, break the cavalry out of the pocket at Komarów, and dig in on the Niemen while diplomats at Riga draw a border across the ground your battalions are standing on.",
  "eqp": "eqp-kaiser",
  "file": "polsov.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 11,
  "title": "The Polish-Soviet War (1919-1920)"
 },
 {
  "desc": "November 1936. Franco's columns are in the suburbs, German and Italian aircraft rule the sky, and Madrid is defended by militias who have never fought as an army. Hold the capital, then forge improvised battalions into the Ejército Popular at the Jarama, Guadalajara, Brunete, Aragon and the frozen ruins of Teruel.\n\nIn July 1938 the Republic stakes everything on a night crossing of the Ebro. Win decisively and history breaks open: the offensive rolls on to Zaragoza and then across the Strait to Ceuta, back to the African shore where the rebellion began. Settle for less, and you must weather the fascist counteroffensive and a last stand on the Segre. Twelve battles, and one chance to write a different ending for Spain.",
  "eqp": "eqp-gce",
  "file": "gce.json",
  "flag": 226,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 12,
  "title": "Ejercito Popular (1936-1939)"
 },
 {
  "desc": "Khalkhin Gol, 1939. A little-known Soviet commander gathers tanks, guns and aircraft into a single blow and destroys a Japanese army on the Mongolian steppe. His name is Georgy Zhukov, and the next six years will make it a legend. Follow his war through Moscow, Rzhev, the breaking of the Leningrad blockade, Kursk and the Korsun pocket.\n\nIn the summer of 1944, Stavka lets the Marshal choose his front for Operation Bagration: the 1st Belorussian, through Bobruisk to the Vistula, or the 2nd, through Mogilev, Minsk and Grodno. Both roads lead to Pomerania and the final storm of Berlin. Seventeen operations reward the Zhukov method: meticulous preparation, crushing concentration and the nerve to commit the reserve at exactly the right hour.",
  "eqp": "eqp-comww2",
  "file": "ga4.json",
  "flag": 89,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 17,
  "title": "Zhukov: Red God of War (1939-1945)"
 },
 {
  "desc": "Capua, 73 BC. A handful of gladiators break out of their school with kitchen knives and nothing to lose. Within a year they are an army: they rout Rome's troops on the slopes of Vesuvius, sack Nola and Nuceria, and send praetor after praetor fleeing.\n\nThen, in 72 BC, the revolt splits, and you must choose. March with Crixus and the Celts to strike at Rome in its own heartland, or follow Spartacus north towards the Alps and freedom. Both roads end with Crassus and his legions walling the rebels into the south of Italy. Nineteen battles ask whether slaves can outfight the legions long enough to overturn the verdict of history.",
  "eqp": "eqp-ag",
  "file": "spa.json",
  "flag": 310,
  "deployphase": false,
  "prestige": 10,
  "scenarios": 19,
  "title": "Spartacus: The Slave Revolt (73-71 BC)"
 },
 {
  "desc": "December 1964. Your fighters strike at Binh Gia, and by first light the enemy is hunting them. This is a war in which the other side owns the sky, the artillery and the roads. You own the night, the jungle and time.\n\nTwelve operations span eleven years: the siege of Plei Me and the valley of Ia Drang, clashes with South Korean troops on the coast, Khe Sanh, the Tet Offensive in Hue and Da Nang, the 1971 fight for the supply lines in Laos and the battle for Kontum. Strike, vanish, strike again, until April 1975 and the final advance on Saigon.",
  "eqp": "eqp-olgcw",
  "file": "nvc.json",
  "flag": 276,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 12,
  "title": "Viet Cong (1964-1975)"
 },
 {
  "desc": "22 June 1941, on the river Prut. The first shots of the southern front are fired here, and it will be three years before Soviet troops stand on this riverbank again. In between lies the fight for the Black Sea coast: Odessa under siege, Perekop, the winter landings in Crimea, Sevastopol, and the Caucasus passes where the German drive for the oil finally breaks.\n\nTwenty-seven operations turn a retreat into the long road back. Choose where the Crimean counteroffensive of 1941 goes ashore: Kerch or Feodosiya. Hold Sukhumi and Ordzhonikidze, retake Maikop, Rostov and Novorossiysk, clear the Taman peninsula, return to Odessa and Sevastopol as liberators, and carry the offensive back across the Prut to Bucharest and Sofia.",
  "eqp": "eqp-basekorp",
  "file": "rcampdfr.json",
  "flag": 61,
  "deployphase": true,
  "prestige": 500,
  "scenarios": 27,
  "title": "Soviet Black Sea Fleet (1941-1944)"
 },
 {
  "desc": "August 1927. In Nanchang, Nationalist regiments turn their guns on their own commanders, and the Chinese Red Army is born fighting for its life. Survive the Autumn Harvest Uprising and the encirclement campaigns in the Jinggang Mountains, seize Luding Bridge on the Long March, ambush the Japanese at Pingxingguan and launch the Hundred Regiments Offensive.\n\nThe civil war is only the midpoint. Cross into Korea, where only a decisive result at Seoul reopens the road to Pusan. Then history gives way: an invasion of Taiwan under the shadow of nuclear crisis, a Soviet army across the Amur and, in Beijing in 1955, a KGB offer to overthrow Mao himself. From a mutiny to a coup, how far will your loyalty to the revolution go?",
  "eqp": "eqp-olgww2",
  "file": "rsoc.json",
  "flag": 21,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 19,
  "title": "Red Star Over China (1927-1949)"
 },
 {
  "desc": "November 1942. On the Chir, west of Stalingrad, Operation Uranus has torn open the Axis front, and a Soviet Guards tank corps is ordered through the gap. Its war will not stop until Berlin.\n\nTwenty operations test everything deep battle demands: meeting the panzers at Prokhorovka, racing for Kiev and Zhitomir, encircling armies in Belorussia and fighting district by district into the capital of the Reich. Prestige flows freely enough to build the formidable combined-arms corps of history: T-34s, motorised infantry, self-propelled guns, engineers and Guards. Fuel, losses and timing decide whether it reaches the finish.",
  "eqp": "eqp-adlerkorps",
  "file": "062d.json",
  "flag": 61,
  "prestige": 4000,
  "scenarios": 20,
  "title": "The Great Patriotic War USSR Campaign (1942-1945)"
 },
 {
  "desc": "You are Zhukov, and the German Sixth Army has just walked into your trap at Stalingrad. Close the ring, smash the Axis front on the Don, and roll south to Rostov, Sevastopol and Odessa, then back through Kharkov and Kiev to the Oder and the last fortress of the Reich: the Reichstag.\n\nThis is where history stops and this campaign keeps going. Weeks after the victory, the Western Allies open fire in Berlin, and Moscow answers with the unthinkable: a new Pact of Steel with its German and Italian enemies. Drive the Allies into the sea at Dunkirk, cross the Channel, take Windsor and London, then carry the war over the Atlantic to Florida, Savannah and, at last, Washington. Twenty-seven operations from the Volga to the Potomac.",
  "eqp": "eqp-adlerkorps",
  "file": "camp6.json",
  "flag": 61,
  "prestige": 500,
  "scenarios": 27,
  "title": "Soviet Counter-Offensive Campaign (1942-1946)"
 },
 {
  "desc": "October 1940. Mussolini expects Greece to fall in a fortnight. Instead, your troops throw the Italians back across the Pindus and deep into Albania. Then the Wehrmacht arrives. Choose whether to face the German onslaught with the Central or the Western Macedonia Army, make a last stand at Thermopylae, and meet the paratroopers falling on Crete. Beat them there, and there will be no evacuation.\n\nAfter El Alamein comes the decision that splits the campaign, and the country, in two. Serve the Greek government from the Alexandria mutiny to the Gothic Line in Italy, or break out of a military prison in Alexandria to join ELAS in the mountains, trading your old core for new fighters of equal experience. Both roads lead to Athens in December 1944 and into the civil war, where the same battles are fought from opposite sides of the line. Companions who share your story remember what you chose.",
  "eqp": "eqp-lxf",
  "file": "camp6bn4.json",
  "flag": 39,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 29,
  "title": "Greece: Resistance and Civil War (1940-1949)"
 },
 {
  "desc": "Forward: the only order that never changes. Forty-four scenarios carry your Soviet army from Khalkhin Gol and the Finnish winter into the disaster of 1941: the pockets at Minsk, Kiev and Bryansk, and the last line before Moscow.\n\nThen the war begins to branch. A brilliant victory at Tula can trap Army Group Centre and end the war in 1942; a weak one throws you into street fighting in Moscow itself. After Kharkov, choose which German army group to hunt to the end: north to Leningrad, Riga and Courland; south through the Kuban, Romania and Hungary to Prague; or through the centre to the Oder, where the result at Küstrin decides between Berlin and a new war against the Western Allies, with German divisions fighting beside you or against you. Two of the three roads end in Manchuria.",
  "eqp": "eqp-atomic",
  "file": "forward.json",
  "flag": 89,
  "deployphase": true,
  "prestige": 2300,
  "scenarios": 44,
  "title": "Forward, Comrade! (1939-1945)"
 },
 {
  "desc": "You are a Red commander on the Eastern Front, and for the first year of it you will be defending things you have been told cannot be held. The Czechoslovak corps has taken the Volga bridge on its way home, a committee of Constituent Assembly deputies is governing Russia out of Samara, and behind them come Kolchak, the Siberian Cossacks and six thousand versts of railway.\n\nTwenty-three operations from the Volga to Irkutsk. Hold Kazan with six hundred million roubles of Imperial gold in the vaults beneath it and a Fifth Army that has barely been formed. Survive a Urals winter at thirty below at Ufa, Khanzhin's spring offensive coming out of the thaw, and Dutov's Cossacks around Orenburg.\n\nThen Frunze turns the front around, and for a year the arrows on the map run east. Chapayev's division crosses the Belaya on rafts at Ufa. Ekaterinburg, and the house on Voznesensky Lane. Chelyabinsk, held at both shoulders at once. The Tobol, where the enemy's last offensive runs out of everything. And after Omsk, the Great Siberian Ice March coming down a single railway, until it ends at Irkutsk, with the Supreme Ruler in a prison cell and the remains of the gold reserve in the same town.\n\nA bad result at Chistopol does not end the campaign. It opens an emergency line of defences back towards Moscow: Kazan, Samara, Vyatka, Saratov, Ryazan, Klin. Hold any one of them and you return at once to the counteroffensive. The title is the enemy's own motto, taken from his banner.",
  "eqp": "eqp-kaiser",
  "file": "simpob.json",
  "flag": 103,
  "deployphase": false,
  "prestige": 300,
  "scenarios": 23,
  "title": "Sim Pobedishi! - The Red East (1918-1920)"
 }
]
