package org.osada.hero

import org.osada.hero.HeroBiographySentences.genderedFact
import org.osada.hero.HeroBiographySentences.genderedSelector
import org.osada.hero.HeroBiographySentences.origin
import org.osada.hero.HeroBiographySentences.variantKey
import org.osada.i18n.I18n

/**
 * Composes [HeroBiographyFacts] into the dossier's `Personal record` block — the biography design's
 * §13.1, built on `docs/design/hero-presentation.md` §2.3b's original two-sentence renderer.
 *
 * ## Two paths, and why the old one survives
 *
 * A hero generated before the life-path system has no [HeroBiographyFacts.biographyPackId], and is
 * narrated by [legacyRecord] exactly as they always were. That is §15's stated migration policy —
 * "preserve ... never reroll a character the player already knows" — expressed as a rendering
 * branch rather than a save migration: nothing about an existing hero is touched, so nothing about
 * them can change. A hero generated by [HeroLifePath] takes [lifePathRecord] and gets up to four
 * sentences: origin, schooling, entry into service, and the optional political / prior-service line.
 *
 * ## Deterministic
 *
 * A pure function of the stored facts and a rank id, with no randomness at display time (§17.1).
 * All the selection happened once, at generation, and is baked into the ids.
 *
 * ## Composable in both locales, not fragment-concatenated
 *
 * Every sentence is one [I18n.select] branch with named slots, chosen by which facts are present —
 * never built by splicing separately-translated clauses together in English word order, which is
 * how translated text becomes ungrammatical. Adding a fact means adding a branch, not a `+`.
 *
 * **A null field renders as an omitted clause, not as "unknown"** (§13.1) — and a sentence with
 * nothing to say is omitted whole rather than rendered empty.
 *
 * ## Gendered (§4.11)
 *
 * [seed] is the hero's portrait seed — the same one [PortraitComposerV2.genderFor] rolls a gender
 * from — so the biography's pronouns always agree with the face. An **authored** hero passes
 * `femaleOverride` instead (from [PortraitComposition.female]): their face is a painting, not a
 * roll, so the painting is what the prose has to agree with. Selector branches carry a `_f`
 * sibling; fact clauses looked up directly fall back from a `_f` key to the base key via
 * [I18n.tOrNull], so a language whose nouns do not inflect needs no redundant feminine copies.
 */
internal object HeroBiographyNarrator {
    fun narrate(
        facts: HeroBiographyFacts,
        rankId: String,
        seed: Int,
        femaleOverride: Boolean? = null,
    ): List<String> {
        val female = femaleOverride ?: (PortraitComposerV2.genderFor(seed) == "female")
        return if (facts.biographyPackId == null) {
            legacyRecord(facts, rankId, female)
        } else {
            lifePathRecord(facts, rankId, female)
        }
    }

    // --------------------------------------------------------------- life path

    private fun lifePathRecord(
        facts: HeroBiographyFacts,
        rankId: String,
        female: Boolean,
    ): List<String> {
        val variant = facts.biographyPackId?.let(BiographyPacks::byId)?.narrationVariant
        return listOfNotNull(
            origin(facts, female),
            schoolingSentence(facts, female, variant),
            enteredSentence(facts, rankId, female, variant),
            recordSentence(facts, female),
        )
    }

    /** Schooling and the civilian trade it led to — §7.3's first two sections. */
    private fun schoolingSentence(
        facts: HeroBiographyFacts,
        female: Boolean,
        variant: String?,
    ): String? {
        val education = facts.civilianEducationId?.let { genderedFact("hero.bio.civedu.$it", female) }
        val profession = facts.prewarProfessionId?.let { genderedFact("hero.bio.profession.$it", female) }
        val selector =
            when {
                education != null && profession != null -> "education_profession"
                education != null -> "education_only"
                profession != null -> "profession_only"
                else -> return null
            }
        return I18n.select(
            variantKey("hero.bio.schooling", variant),
            genderedSelector(selector, female),
            mapOf("education" to education, "profession" to profession),
        )
    }

    /**
     * How the officer came into the army, when, and what training they were given — §8.4's
     * "entered military service", kept distinct from the war-entry clause in [recordSentence].
     */
    private fun enteredSentence(
        facts: HeroBiographyFacts,
        rankId: String,
        female: Boolean,
        variant: String?,
    ): String? {
        val entry = facts.serviceEntryId?.let { genderedFact("hero.bio.entry.$it", female) }
        // `hero.bio.miledu.*`, not the legacy `hero.bio.education.*`: those values are worded to
        // OPEN the legacy commission sentence ("Commissioned from the ranks, he rose to major."),
        // and this sentence needs the same fact as a mid-sentence clause. Rewording the shared key
        // would silently change how every pre-life-path hero already in a save reads.
        val education = facts.militaryEducationId?.let { genderedFact("hero.bio.miledu.$it", female) }
        val year = facts.serviceStartYear
        val selector =
            when {
                entry != null && year != null && education != null -> "entry_year_education"
                entry != null && year != null -> "entry_year"
                entry != null && education != null -> "entry_education"
                entry != null -> "entry"
                education != null -> "education"
                else -> return null
            }
        return I18n.select(
            variantKey("hero.bio.entered", variant),
            genderedSelector(selector, female),
            mapOf(
                "entry" to entry,
                "year" to year?.toString(),
                "education" to education,
                "rank" to HeroDisplay.rank(rankId),
            ),
        )
    }

    /**
     * The optional closing line: how they reached this war, party status, rare prior service.
     *
     * The `when` is seven branches because three optional clauses are seven combinations, and each
     * one is a whole translated sentence. Collapsing it would mean concatenating clauses in English
     * word order -- exactly what §14 forbids.
     */
    @Suppress("CyclomaticComplexMethod")
    private fun recordSentence(
        facts: HeroBiographyFacts,
        female: Boolean,
    ): String? {
        val war = facts.warEntryId?.let { genderedFact("hero.bio.warentry.$it", female) }
        val political = politicalClause(facts, female)
        val service = priorServiceClause(facts, female)
        val selector =
            when {
                war != null && political != null && service != null -> "war_political_service"
                war != null && political != null -> "war_political"
                war != null && service != null -> "war_service"
                war != null -> "war"
                political != null && service != null -> "political_service"
                political != null -> "political"
                service != null -> "service"
                else -> return null
            }
        return I18n.select(
            "hero.bio.record",
            genderedSelector(selector, female),
            mapOf("war" to war, "political" to political, "service" to service),
        )
    }

    /**
     * `Non-party.` or `Party member since 1920.` — §8.5's two forms, and nothing more institutional
     * than that. An undated membership falls back to an `_undated` key rather than printing a
     * placeholder year, which is the same "omit, never guess" rule the rest of the file follows.
     */
    @Suppress("ReturnCount") // three guard clauses: absent, undated, dated -- nesting them reads worse
    private fun politicalClause(
        facts: HeroBiographyFacts,
        female: Boolean,
    ): String? {
        val id = facts.politicalStatusId ?: return null
        val year = facts.politicalMembershipYear
        val args = mapOf("year" to year?.toString())
        if (year == null) {
            I18n.tOrNull("hero.bio.political.${id}_undated")?.let { return it }
        }
        return (if (female) I18n.tOrNull("hero.bio.political.${id}_f", args) else null)
            ?: I18n.t("hero.bio.political.$id", args)
    }

    /**
     * One or two prior conflicts, joined by a localized conjunction rather than a hard-coded
     * `" and "` — the join is itself a translated template with two slots, so a language that
     * orders or punctuates a pair differently can say so.
     */
    private fun priorServiceClause(
        facts: HeroBiographyFacts,
        female: Boolean,
    ): String? {
        val clauses = facts.priorServiceIds.map { genderedFact("hero.bio.service.$it", female) }
        return when (clauses.size) {
            0 -> null
            1 -> clauses[0]
            else -> I18n.t("hero.bio.service_pair", mapOf("first" to clauses[0], "second" to clauses[1]))
        }
    }

    // ------------------------------------------------------------------ legacy

    /** The pre-life-path renderer, kept verbatim for heroes already in saves (§15). */
    private fun legacyRecord(
        facts: HeroBiographyFacts,
        rankId: String,
        female: Boolean,
    ): List<String> = listOfNotNull(origin(facts, female), commissionSentence(facts, rankId, female))

    private fun commissionSentence(
        facts: HeroBiographyFacts,
        rankId: String,
        female: Boolean,
    ): String {
        val rank = HeroDisplay.rank(rankId)
        val education = facts.militaryEducationId?.let { genderedFact("hero.bio.education.$it", female) }
        val service = facts.priorServiceIds.firstOrNull()?.let { genderedFact("hero.bio.service.$it", female) }
        val selector =
            when {
                education != null && service != null -> "education_service"
                education != null -> "education_only"
                service != null -> "service_only"
                else -> "none"
            }
        return I18n.select(
            "hero.bio.commission",
            genderedSelector(selector, female),
            mapOf("rank" to rank, "education" to education, "service" to service),
        )
    }
}
