package org.osada.scenario

import org.osada.i18n.I18n

/**
 * Translations for the authored prose a scenario shows **during the battle**: `<event message>`
 * and `<reinforce message>`.
 *
 * Those two strings live in the scenario XML, which is a faithful record of what the author wrote
 * and is regenerated by the importers -- so a translation cannot live there without being erased
 * on the next import, and could not be per-language anyway. They travel in an [I18n] domain of
 * their own instead, `i18n/<lang>/scenarios/<stem>.json`, exactly as a campaign's briefing prose
 * does in `briefings/<campaign>/<scenario>.json`
 * ([org.osada.ui.briefing.BriefingLocalization]).
 *
 * [LOCALIZED] is an explicit allow-list rather than "try to fetch and see", for the same reason
 * `BriefingLocalization` keeps one: 502 scenarios ship and a speculative fetch per battle would be
 * 501 console 404s. A scenario gains a translation by being added here alongside its bundle.
 *
 * Every lookup falls back to the authored English, so a missing key, an unloaded bundle or an
 * untranslated scenario all degrade to exactly what the game showed before.
 */
internal object ScenarioTextLocalization {
    /** Scenario file stems with a `scenarios/<stem>.json` bundle. Currently the one scenario in the
     *  shipped corpus that authors any in-battle message at all. */
    private val LOCALIZED = setOf("n_kiel")

    /** Loads this scenario's bundle if it has one, then calls back. Called at scenario load so the
     *  strings are in place well before an event can fire; a battle whose scenario has no bundle
     *  calls back immediately without touching the network. */
    fun ensure(
        scenarioFile: String?,
        onReady: () -> Unit = {},
    ) {
        val domain = domain(scenarioFile)
        if (domain == null) onReady() else I18n.ensureDomain(domain, onReady)
    }

    /** The authored `<event message>`, translated where a translation exists. */
    fun eventMessage(
        scenarioFile: String?,
        eventId: String,
        authored: String,
    ): String = resolve(scenarioFile, "event.$eventId.message", authored)

    /** The authored `<reinforce message>` for [turn], translated where a translation exists. */
    fun reinforcementMessage(
        scenarioFile: String?,
        turn: Int,
        authored: String,
    ): String = resolve(scenarioFile, "reinforce.$turn.message", authored)

    private fun resolve(
        scenarioFile: String?,
        key: String,
        authored: String,
    ): String {
        val domain = domain(scenarioFile) ?: return authored
        return I18n.tOrNull(key, domain = domain) ?: authored
    }

    private fun domain(scenarioFile: String?): String? =
        stem(scenarioFile)?.takeIf { it in LOCALIZED }?.let { "scenarios/$it" }

    /** `resources/.../n_kiel.xml` -> `n_kiel`; the same normalisation the briefing domain uses, so
     *  a bundle is named after the file id the rest of the game already keys on. */
    private fun stem(file: String?): String? =
        file
            ?.substringAfterLast('/')
            ?.substringAfterLast('\\')
            ?.substringBeforeLast('.')
            ?.lowercase()
            ?.replace(Regex("[^a-z0-9_-]"), "-")
            ?.takeIf { it.isNotBlank() }
}
