package org.osada.model

import org.w3c.xhr.XMLHttpRequest
import kotlin.js.Json

/**
 * Per-efile equipment overrides: a field value that applies only while a given efile is the active
 * one, leaving the merged record itself untouched for every other campaign.
 *
 * **Why this exists.** `eqp-united` is one merged database, so a record contributed by more than one
 * efile is literally the same object in every campaign that can field it. Fixing `36 Gornostrelky`
 * for the two Panzer Marshal campaigns therefore also edited it for "Soviet Black Sea Fleet", which
 * the owner ruled out: *"no changes across all campaigns, only those two. If it touches others,
 * revert the edit."* Reverting left those records visibly inconsistent beside their PM-only
 * neighbours -- `41 Gornostrelky` mountain-trained, `36 Gornostrelky` not -- which is the question
 * this answers: *"can you give MTN to the mountain troops, PTZ to the partisans, HQ to the HQs and
 * NKVD, and take MAR off the paratroops, for these PM campaigns only?"*
 *
 * **Scope is the efile, not the campaign**, which is the same granularity
 * [EquipmentAvailability]'s allowlist already uses and the same key: `Equipment.name`, set from the
 * scenario's `eqp` attribute (`ScenarioLoader`) or a save's stored value (`GameStateRestore`),
 * always BEFORE `addPlayersEquipment` parses a single country file. `eqp-adlerkorps` is reachable
 * from exactly the two campaigns in question, so efile scope and campaign scope coincide here.
 *
 * **Applied at parse time**, in [Equipment.parseCountryEquipment], so every reader -- combat, the
 * purchase window, the unit card, the AI's own buy filter -- sees one consistent record and none of
 * them needs to know overrides exist. `resetEquipment()` runs per scenario load, so switching to a
 * campaign on another efile re-parses from the untouched JSON and nothing leaks across.
 *
 * The file is GENERATED by `tools/eqp-merge/pm_content_patch.py` from the same name rules that edit
 * the PM-only records directly -- one source of truth for "what a Gornostrelky is", two delivery
 * mechanisms depending on whether the record is shared. Hand-editing it will be overwritten.
 */
internal object EquipmentOverrides {
    /** `{efile: {eqid: {field: value}}}`, null until the first load attempt resolves. */
    private var map: Map<String, Map<Int, Map<String, Int>>>? = null
    private var loadAttempted = false

    /** Fields an override may set. Deliberately a closed list: an override is a content patch, not
     *  a second equipment format, and silently accepting `cost` or `uclass` here would let one
     *  become a re-balance nobody reviewed. */
    private val ALLOWED_FIELDS = setOf("attr", "attr2", "attrEx", "embark", "movmethod")

    private fun loadIfNeeded() {
        if (loadAttempted) return
        loadAttempted = true
        val text = fetchText()
        if (!text.isNullOrBlank()) map = parse(JSON.parse(text))
    }

    /** Synchronous, like [EquipmentAvailability]'s own fetch and for the same reason: one small
     *  file, read once per session, before any country file is parsed. An absent file is not an
     *  error -- a tree with no overrides at all is the normal case. */
    private fun fetchText(): String? {
        val path = "${Equipment.EQUIPMENT_PATH}${Equipment.UNITED_NAME}/overrides.json"
        val request = XMLHttpRequest()
        request.open("GET", path, false)
        request.send(null)
        val status = request.status.toInt()
        return if (status in Equipment.httpSuccessRange || status == 0) request.responseText else null
    }

    private fun parse(json: Json): Map<String, Map<Int, Map<String, Int>>> {
        val result = mutableMapOf<String, Map<Int, Map<String, Int>>>()
        js("Object.keys")(json).unsafeCast<Array<String>>().forEach { efile ->
            if (efile.startsWith("_")) return@forEach // `_note` and friends are documentation
            val byEqid = json.asDynamic()[efile]
            val records = mutableMapOf<Int, Map<String, Int>>()
            js("Object.keys")(byEqid).unsafeCast<Array<String>>().forEach { key ->
                val eqid = key.toIntOrNull() ?: return@forEach
                val fieldsJson = byEqid[key]
                val fields = mutableMapOf<String, Int>()
                js("Object.keys")(fieldsJson).unsafeCast<Array<String>>().forEach { field ->
                    val value = (fieldsJson[field] as? Number)?.toInt()
                    if (field in ALLOWED_FIELDS && value != null) fields[field] = value
                }
                if (fields.isNotEmpty()) records[eqid] = fields
            }
            result[efile] = records
        }
        return result
    }

    /** Applies the active efile's override for [eqid] to [data], in place. No-op when there is none. */
    fun apply(
        eqid: Int,
        data: EquipmentData,
    ) {
        loadIfNeeded()
        val fields = map?.get(Equipment.name)?.get(eqid) ?: return
        fields.forEach { (field, value) ->
            when (field) {
                "attr" -> data.attr = value
                "attr2" -> data.attr2 = value
                "attrEx" -> data.attrEx = value
                "embark" -> data.embark = value
                "movmethod" -> data.movmethod = value
            }
        }
    }

    /** Test seam: installs a map directly and suppresses the file read. */
    internal fun setForTest(json: String?) {
        map = json?.let { parse(JSON.parse(it)) }
        loadAttempted = true
    }

    /** Test seam: forces the next [apply] to re-read the file. */
    internal fun resetForTest() {
        map = null
        loadAttempted = false
    }
}
